config/routes.rb
Rails.application.routes.draw do
  resources :feeds
  root 'feeds#index'

end

app/models/feed.rb
class Feed < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  protect_from_forgery except: :create
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.all.order('created_at DESC')
  end

  # GET /feeds/1
  # GET /feeds/1.json
  def show
  end

  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new(feed_params)

    respond_to do |format|
      if @feed.save
        format.html { redirect_to @feed, notice: 'Feed was successfully created.' }
        format.json { render :show, status: :created, location: @feed }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json
  def update
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'Feed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feed
      @feed = Feed.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def feed_params
      params.require(:feed).permit(:name, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/views/feeds/_form.html.erb
<%= form_for(@feed) do |f| %>
  <% if @feed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h2>

      <ul>
      <% @feed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/feeds/edit.html.erb
<h1>Editing Feed</h1>

<%= render 'form' %>

<%= link_to 'Show', @feed %> |
<%= link_to 'Back', feeds_path %>

app/views/feeds/index.html.erb
<section class="deploy-to-tweet">
    <p id="notice"><%= notice %></p>

    <h1>I've deployed using <span class="twitter">twitter</span> <%= image_tag 'tweeter.jpg', class: 'tweet-image' %></h1>
    <div class="how-to">Tweet mentioning <a href="https://twitter.com/snap_ci">@snap_ci</a> with <a href="https://twitter.com/hashtag/deploy?src=hash">#deploy</a> and see your deployments running <a href="https://snap-ci.com/snap-ci-examples/snap_leaderboard/branch/publish">here!</a></div>
    <h5><a href="https://snap-ci.com/snap-ci-examples/snap_leaderboard/branch/publish"><img src="https://snap-ci.com/snap-ci-examples/snap_leaderboard/branch/publish/build_image" alt="Build Status"></a></h5>

    <div class="cool-tweets">
        <table>
          <thead>
            <tr>
              <th>From</th>
              <th>Tweet</th>
            </tr>
          </thead>

          <tbody>
            <% @feeds.each do |feed| %>
              <tr>
                <td><a href="https://twitter.com/<%= feed.name %>">@<%= feed.name %></a></td>
                <td><%= raw feed.message
                                    .gsub(/@(?<arroba>\w+)/, '<a href="https://twitter.com/\k<arroba>">@\k<arroba></a>')
                                    .gsub(/#(?<hashtag>\w+)/, '<a href="https://twitter.com/hashtag/\k<hashtag>?src=hash">#\k<hashtag></a>') %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
    </div>

  <div class="create-your-own">
    <span><a href="https://ifttt.com/recipes/319608-deploy-to-snap-ci-com-from-twitter" target="_blank"> Wanna create your own Twitter -> Snap trigger?</a></span>
  </div>
</section>

app/views/feeds/new.html.erb
<h1>New Feed</h1>

<%= render 'form' %>

<%= link_to 'Back', feeds_path %>

app/views/feeds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @feed.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @feed.message %>
</p>

<%= link_to 'Edit', edit_feed_path(@feed) %> |
<%= link_to 'Back', feeds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tweet to deploy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="refresh" content="15">
</head>
<body>

<%= yield %>

</body>
</html>